DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS users (
    id          integer generated by default as identity primary key,
    name        varchar(50),
    email       varchar(50)
    );
CREATE TABLE IF NOT EXISTS items (
    id          integer generated by default as identity primary key,
    name        varchar(50) not null,
    description varchar(200) not null,
    is_available boolean default true not null,
    owner_id    integer references users (id) on delete cascade
);

